### ISSUE TITLE
Feature Request: React Router support

### ISSUE THREAD

**Issue by nerdstep** [jeff3dx/react-query-params#1]
Hey, I like your component and I'd like to use it with React Router (v4.x), from which they've sadly removed query string support. Looking at your code I think it would be fairly easy to integrate. Do you have any thoughts on this? I'd be happy to submit a pull request if you think it would be a good fit.

**Comment by jeff3dx** [comment]
I verified it working with v4 a while ago but if not and you have it worked out please send the PR!

**Comment by nerdstep** [comment]
After further testing I see that it does work as was probably intended with React Router. The problem from my perspective is that I'm using the `HashRouter` and was expecting it to the read query string from after the hash segments instead of the "true" query string location before the hash route.

I think by adding an additional conditional if statement in the class constructor to look for the history object on the props instead of `this.context.router` and passing `this.props` as the `source` argument to `_resolveSearchParams` it would provide the behavior I'm looking for.

I suppose the question then is whether or not you want to support this use-case?

**Comment by onemenny** [comment]
@nerdstep - this is not the only change needed. also the this.history.push and this.history.replace needs to be changed. 
I would not complicate The current code for this situation - you can easily fork it and alter the code yourself (I did it). This will also work with createHashHistory and react-redux-router

`export default class ReactQueryParams extends Component {
   
    constructor(props) {
        super();
        this.history = props.history;
    }

    /* Clear the query param cache */
    componentWillUpdate() {
        this._queryParamsCache = null;

        if (super.componentWillUpdate) {
            super.componentWillUpdate();
        }
    }

    /**
     * Convert boolean string to boolean type.
     * Any query param set to "true" or "false" will be converted to a boolean type.
     * @param {string} value - the query param string value
     */
    _boolify(value) {
        if (typeof value === "string") {
            const value2 = value.toLowerCase().trim();
            if (value2 === "true") {
                return true;
            } else if (value2 === "false") {
                return false;
            }
        }
        return value;
    }

    /**
     * If query param string is object-like try to parse it
     */
    _queryParamToObject(value) {
        let result = value;
        if (
            typeof value === "string" &&
            ((startsWith(value, "[") && endsWith(value, "]")) ||
                (startsWith(value, "{") && endsWith(value, "}")))
        ) {
            try {
                result = JSON.parse(value);
            } catch (ex) {
                console.error(ex);
                // Can't parse so fall back to verbatim value
                result = value;
            }
        }
        return result;
    }

    _queryParamsCache;

    _resolveSearchParams() {
        let searchParams = {};

        if (this.history.location.search) {
            const urlSearch = new URLSearchParams(this.history.location.search);

            for (let pair of urlSearch) {
                searchParams[pair[0]] = pair[1];
            }
        }
        return searchParams;
    }

    /**
     * Returns a map of all query params including default values. Params that match
     * the default value do not show up in the URL but are still available here.
     */
    get queryParams() {
        if (isNil(this._queryParamsCache)) {
            const searchParams = this._resolveSearchParams();

            const defaults = this.defaultQueryParams || {};
            const all = {...defaults, ...searchParams};
            Object.keys(all).forEach(key => {
                all[key] = this._boolify(all[key]);
                all[key] = this._queryParamToObject(all[key]);
            });
            this._queryParamsCache = all;
        }
        return this._queryParamsCache;
    }

    /**
     * Get one query param value.
     * @param {string} key - The query param key
     */
    getQueryParam(key) {
        const defaults = this.defaultQueryParams || {};
        const searchParams = this._resolveSearchParams();
        let result = isUndefined(searchParams[key])
            ? searchParams[key]
            : defaults[key];
        result = this._boolify(result);
        result = this._queryParamToObject(result);
        return result;
    }

    /**
     * Set query param values. Merges changes similar to setState().
     * @param {object} params - Object of key:values to overlay on current query param values.
     * @param {boolean} addHistory - true = add browser history, default false.
     */
    setQueryParams(params, addHistory = false) {
        const searchParams = this._resolveSearchParams();

        const nextQueryParams = {...searchParams, ...params};
        const defaults = this.defaultQueryParams || {};

        Object.keys(nextQueryParams).forEach(key => {
            // If it's an object value (object, array, etc.) convert it to a string
            if (isObject(nextQueryParams[key])) {
                try {
                    nextQueryParams[key] = JSON.stringify(nextQueryParams[key]);
                } catch (ex) {
                    console.log(
                        "react-query-params -- Failed to serialize queryParam " + key,
                        ex
                    );
                    nextQueryParams[key] = "";
                }
            }
            // Remove params that match the default
            if (nextQueryParams[key] === defaults[key]) {
                delete nextQueryParams[key];
            }
        });

        const search =
            "?" +
            Object.keys(nextQueryParams)
                .map(key => `${key}=${nextQueryParams[key]}`)
                .join("&");

        if (addHistory) {
            this.history.push(this.history.location.pathname + search);
        } else {
            this.history.replace(this.history.location.pathname + search);
        }

        // Clear the cache
        this._queryParamsCache = null;

        this.forceUpdate();
    }
}`

**Comment by nerdstep** [comment]
@onemenny Thanks, yeah that's effectively what I've done. No need to keep this issue open as far as I'm concerned.
